package models

import (
	"time"
)

type Transaction struct {
	ID                uint      `gorm:"primaryKey" json:"id"`
	UserID            uint      `gorm:"not null;index" json:"user_id"`
	Reference         string    `gorm:"not null;uniqueIndex" json:"reference"` // Internal idempotency/reference key
	Amount            float64   `gorm:"type:decimal(20,4);not null" json:"amount"`
	Fee               float64   `gorm:"type:decimal(20,4);not null;default:0" json:"fee"`
	BalanceAfter      float64   `gorm:"type:decimal(20,4);not null;default:0" json:"balance_after"`
	Currency          string    `gorm:"not null;size:10" json:"currency"`
	SettledAmount     float64   `gorm:"type:decimal(20,4);default:0" json:"settled_amount"`
	SettledCurrency   string    `gorm:"size:10" json:"settled_currency"`
	PaymentMethod     string    `gorm:"size:20" json:"payment_method"` // fiat, crypto
	Type              string    `gorm:"not null;size:50;index" json:"type"`   // deposit, withdrawal, transfer, payment_link_payment, invoice_payment
	Status            string    `gorm:"not null;size:20;index" json:"status"` // pending, successful, failed
	IsTest            bool      `gorm:"default:false;index" json:"is_test"`
	Provider          string    `gorm:"size:50;index" json:"provider"`        // onepipe, flutterwave, circle, internal, test
	ProviderReference string    `gorm:"size:255;index" json:"provider_reference"` // The reference generated by the provider
	Customer          string    `gorm:"size:255" json:"customer"`       // Email or ID for the UI
	Description       string    `gorm:"type:text" json:"description"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
